# Generated by Django 3.0.2 on 2020-06-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created', 'name'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
