# Generated by Django 3.0.2 on 2020-06-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200625_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, verbose_name='Скидка в %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
