# Generated by Django 3.0.2 on 2020-06-27 11:08

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200626_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='com',
            field=models.CharField(blank=True, max_length=300, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Номер телефона', max_length=31, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=350, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
