# Generated by Django 3.0.2 on 2020-06-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200627_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=350, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='com',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, help_text='Номер телефона', max_length=13, verbose_name='Телефон'),
        ),
    ]
