# Generated by Django 3.0.2 on 2020-07-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200627_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=350, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='com',
            field=models.CharField(blank=True, max_length=350, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Телефон'),
        ),
    ]
